import { Site, SiteCapabilities, EnrollmentHistory } from "./types.js";

export const sites: Site[] = [
  {
    site_id: "SITE-001",
    site_name: "Massachusetts General Hospital Clinical Research Center",
    location: {
      city: "Boston",
      state: "MA",
      country: "USA",
      region_id: "US-NE-001",
    },
    capacity: {
      max_concurrent_trials: 25,
      available_slots: 8,
      patient_enrollment_capacity: 500,
    },
    therapeutic_areas: ["Endocrinology", "Cardiology", "Oncology", "Neurology"],
  },
  {
    site_id: "SITE-002",
    site_name: "Brigham and Women's Hospital Research Institute",
    location: {
      city: "Boston",
      state: "MA",
      country: "USA",
      region_id: "US-NE-001",
    },
    capacity: {
      max_concurrent_trials: 30,
      available_slots: 5,
      patient_enrollment_capacity: 600,
    },
    therapeutic_areas: ["Cardiology", "Immunology", "Rheumatology", "Endocrinology"],
  },
  {
    site_id: "SITE-003",
    site_name: "Mount Sinai Clinical Trials Unit",
    location: {
      city: "New York",
      state: "NY",
      country: "USA",
      region_id: "US-NE-002",
    },
    capacity: {
      max_concurrent_trials: 35,
      available_slots: 12,
      patient_enrollment_capacity: 750,
    },
    therapeutic_areas: ["Oncology", "Endocrinology", "Gastroenterology", "Pulmonology"],
  },
  {
    site_id: "SITE-004",
    site_name: "NYU Langone Clinical Research Center",
    location: {
      city: "New York",
      state: "NY",
      country: "USA",
      region_id: "US-NE-002",
    },
    capacity: {
      max_concurrent_trials: 28,
      available_slots: 9,
      patient_enrollment_capacity: 550,
    },
    therapeutic_areas: ["Neurology", "Psychiatry", "Oncology", "Cardiology"],
  },
  {
    site_id: "SITE-005",
    site_name: "UCSF Clinical Research Center",
    location: {
      city: "San Francisco",
      state: "CA",
      country: "USA",
      region_id: "US-CA-001",
    },
    capacity: {
      max_concurrent_trials: 32,
      available_slots: 11,
      patient_enrollment_capacity: 650,
    },
    therapeutic_areas: ["Oncology", "Infectious Disease", "Neurology", "Immunology"],
  },
  {
    site_id: "SITE-006",
    site_name: "Stanford Clinical Trials Center",
    location: {
      city: "Palo Alto",
      state: "CA",
      country: "USA",
      region_id: "US-CA-001",
    },
    capacity: {
      max_concurrent_trials: 30,
      available_slots: 7,
      patient_enrollment_capacity: 600,
    },
    therapeutic_areas: ["Cardiology", "Oncology", "Endocrinology", "Genetics"],
  },
  {
    site_id: "SITE-007",
    site_name: "Cedars-Sinai Medical Center Research Institute",
    location: {
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      region_id: "US-CA-002",
    },
    capacity: {
      max_concurrent_trials: 40,
      available_slots: 15,
      patient_enrollment_capacity: 800,
    },
    therapeutic_areas: ["Oncology", "Cardiology", "Gastroenterology", "Pulmonology"],
  },
  {
    site_id: "SITE-008",
    site_name: "MD Anderson Cancer Center Clinical Trials Office",
    location: {
      city: "Houston",
      state: "TX",
      country: "USA",
      region_id: "US-TX-001",
    },
    capacity: {
      max_concurrent_trials: 50,
      available_slots: 18,
      patient_enrollment_capacity: 1000,
    },
    therapeutic_areas: ["Oncology", "Hematology"],
  },
  {
    site_id: "SITE-009",
    site_name: "Baylor College of Medicine Clinical Research Center",
    location: {
      city: "Houston",
      state: "TX",
      country: "USA",
      region_id: "US-TX-001",
    },
    capacity: {
      max_concurrent_trials: 27,
      available_slots: 10,
      patient_enrollment_capacity: 550,
    },
    therapeutic_areas: ["Endocrinology", "Cardiology", "Nephrology", "Pediatrics"],
  },
  {
    site_id: "SITE-010",
    site_name: "University of Miami Clinical Research Center",
    location: {
      city: "Miami",
      state: "FL",
      country: "USA",
      region_id: "US-FL-001",
    },
    capacity: {
      max_concurrent_trials: 24,
      available_slots: 8,
      patient_enrollment_capacity: 480,
    },
    therapeutic_areas: ["Infectious Disease", "Endocrinology", "Cardiology", "Oncology"],
  },
];

export const siteCapabilities: SiteCapabilities[] = [
  {
    site_id: "SITE-001",
    site_name: "Massachusetts General Hospital Clinical Research Center",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
      "Joint Commission Accredited",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "SPECT", "Ultrasound"],
      laboratory: ["Central Lab", "Pharmacology Lab", "Genomics Lab"],
      specialized: ["Cardiac Cath Lab", "Infusion Center", "Sleep Lab"],
    },
    staff: {
      principal_investigators: 12,
      sub_investigators: 28,
      research_coordinators: 45,
      regulatory_specialists: 8,
    },
    investigator_qualifications: {
      board_certified: 0.95,
      avg_years_experience: 15,
      publications: 234,
    },
  },
  {
    site_id: "SITE-002",
    site_name: "Brigham and Women's Hospital Research Institute",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
      "AAHRPP Accredited",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "Echocardiography"],
      laboratory: ["Central Lab", "Immunology Lab", "Pharmacology Lab"],
      specialized: ["Cardiac Cath Lab", "Infusion Center", "Rheumatology Suite"],
    },
    staff: {
      principal_investigators: 15,
      sub_investigators: 32,
      research_coordinators: 52,
      regulatory_specialists: 10,
    },
    investigator_qualifications: {
      board_certified: 0.97,
      avg_years_experience: 18,
      publications: 312,
    },
  },
  {
    site_id: "SITE-003",
    site_name: "Mount Sinai Clinical Trials Unit",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "Ultrasound", "Endoscopy"],
      laboratory: ["Central Lab", "Oncology Lab", "Molecular Diagnostics"],
      specialized: ["Infusion Center", "GI Suite", "Bronchoscopy Suite"],
    },
    staff: {
      principal_investigators: 18,
      sub_investigators: 40,
      research_coordinators: 65,
      regulatory_specialists: 12,
    },
    investigator_qualifications: {
      board_certified: 0.94,
      avg_years_experience: 16,
      publications: 278,
    },
  },
  {
    site_id: "SITE-004",
    site_name: "NYU Langone Clinical Research Center",
    certifications: [
      "ACRP Certified",
      "CLIA Certified",
      "Joint Commission Accredited",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "fMRI", "MEG"],
      laboratory: ["Central Lab", "Neuroscience Lab"],
      specialized: ["Neuropsychology Suite", "Infusion Center", "Sleep Lab"],
    },
    staff: {
      principal_investigators: 14,
      sub_investigators: 30,
      research_coordinators: 48,
      regulatory_specialists: 9,
    },
    investigator_qualifications: {
      board_certified: 0.96,
      avg_years_experience: 17,
      publications: 256,
    },
  },
  {
    site_id: "SITE-005",
    site_name: "UCSF Clinical Research Center",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
      "AAHRPP Accredited",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "SPECT"],
      laboratory: ["Central Lab", "Infectious Disease Lab", "Immunology Lab", "Genomics Lab"],
      specialized: ["Infusion Center", "Biosafety Level 3 Lab"],
    },
    staff: {
      principal_investigators: 16,
      sub_investigators: 35,
      research_coordinators: 58,
      regulatory_specialists: 11,
    },
    investigator_qualifications: {
      board_certified: 0.95,
      avg_years_experience: 19,
      publications: 342,
    },
  },
  {
    site_id: "SITE-006",
    site_name: "Stanford Clinical Trials Center",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "Cardiac MRI"],
      laboratory: ["Central Lab", "Genomics Lab", "Proteomics Lab"],
      specialized: ["Cardiac Cath Lab", "Infusion Center", "Genetics Counseling Center"],
    },
    staff: {
      principal_investigators: 15,
      sub_investigators: 33,
      research_coordinators: 55,
      regulatory_specialists: 10,
    },
    investigator_qualifications: {
      board_certified: 0.97,
      avg_years_experience: 20,
      publications: 398,
    },
  },
  {
    site_id: "SITE-007",
    site_name: "Cedars-Sinai Medical Center Research Institute",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
      "Magnet Recognition",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "Nuclear Medicine", "Interventional Radiology"],
      laboratory: ["Central Lab", "Oncology Lab", "Cardiology Lab"],
      specialized: ["Cardiac Cath Lab", "Infusion Center", "GI Suite", "Pulmonary Function Lab"],
    },
    staff: {
      principal_investigators: 20,
      sub_investigators: 45,
      research_coordinators: 72,
      regulatory_specialists: 14,
    },
    investigator_qualifications: {
      board_certified: 0.93,
      avg_years_experience: 16,
      publications: 289,
    },
  },
  {
    site_id: "SITE-008",
    site_name: "MD Anderson Cancer Center Clinical Trials Office",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
      "NCI Comprehensive Cancer Center",
    ],
    equipment: {
      imaging: ["MRI", "CT", "PET", "SPECT", "Mammography"],
      laboratory: ["Central Lab", "Molecular Diagnostics", "Pharmacogenomics Lab", "Pathology"],
      specialized: ["Infusion Center", "Radiation Oncology", "Surgical Oncology Suite"],
    },
    staff: {
      principal_investigators: 35,
      sub_investigators: 80,
      research_coordinators: 120,
      regulatory_specialists: 22,
    },
    investigator_qualifications: {
      board_certified: 0.98,
      avg_years_experience: 22,
      publications: 567,
    },
  },
  {
    site_id: "SITE-009",
    site_name: "Baylor College of Medicine Clinical Research Center",
    certifications: [
      "ACRP Certified",
      "CAP Accredited Lab",
      "CLIA Certified",
    ],
    equipment: {
      imaging: ["MRI", "CT", "Ultrasound", "Echocardiography"],
      laboratory: ["Central Lab", "Metabolic Lab", "Nephrology Lab"],
      specialized: ["Cardiac Cath Lab", "Infusion Center", "Dialysis Unit"],
    },
    staff: {
      principal_investigators: 13,
      sub_investigators: 29,
      research_coordinators: 47,
      regulatory_specialists: 9,
    },
    investigator_qualifications: {
      board_certified: 0.94,
      avg_years_experience: 16,
      publications: 221,
    },
  },
  {
    site_id: "SITE-010",
    site_name: "University of Miami Clinical Research Center",
    certifications: [
      "ACRP Certified",
      "CLIA Certified",
    ],
    equipment: {
      imaging: ["MRI", "CT", "Ultrasound"],
      laboratory: ["Central Lab", "Infectious Disease Lab"],
      specialized: ["Infusion Center", "Tropical Medicine Clinic"],
    },
    staff: {
      principal_investigators: 11,
      sub_investigators: 24,
      research_coordinators: 40,
      regulatory_specialists: 7,
    },
    investigator_qualifications: {
      board_certified: 0.92,
      avg_years_experience: 14,
      publications: 187,
    },
  },
];

export const enrollmentHistories: EnrollmentHistory[] = [
  {
    site_id: "SITE-001",
    site_name: "Massachusetts General Hospital Clinical Research Center",
    historical_trials: [
      {
        trial_id: "NCT04123456",
        phase: "Phase III",
        therapeutic_area: "Endocrinology",
        target_enrollment: 50,
        actual_enrollment: 52,
        enrollment_duration_days: 180,
        screen_failure_rate: 0.18,
        dropout_rate: 0.08,
        protocol_deviations: 2,
        completion_year: 2024,
      },
      {
        trial_id: "NCT04234567",
        phase: "Phase II",
        therapeutic_area: "Cardiology",
        target_enrollment: 40,
        actual_enrollment: 43,
        enrollment_duration_days: 150,
        screen_failure_rate: 0.21,
        dropout_rate: 0.09,
        protocol_deviations: 1,
        completion_year: 2023,
      },
      {
        trial_id: "NCT04345678",
        phase: "Phase III",
        therapeutic_area: "Oncology",
        target_enrollment: 60,
        actual_enrollment: 58,
        enrollment_duration_days: 210,
        screen_failure_rate: 0.22,
        dropout_rate: 0.12,
        protocol_deviations: 3,
        completion_year: 2023,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 34,
      avg_enrollment_rate: 1.08,
      avg_screen_failure_rate: 0.21,
      avg_retention_rate: 0.89,
      regulatory_inspection_results: "No findings",
    },
  },
  {
    site_id: "SITE-002",
    site_name: "Brigham and Women's Hospital Research Institute",
    historical_trials: [
      {
        trial_id: "NCT04456789",
        phase: "Phase III",
        therapeutic_area: "Cardiology",
        target_enrollment: 70,
        actual_enrollment: 75,
        enrollment_duration_days: 165,
        screen_failure_rate: 0.19,
        dropout_rate: 0.07,
        protocol_deviations: 1,
        completion_year: 2024,
      },
      {
        trial_id: "NCT04567890",
        phase: "Phase II",
        therapeutic_area: "Rheumatology",
        target_enrollment: 35,
        actual_enrollment: 38,
        enrollment_duration_days: 140,
        screen_failure_rate: 0.20,
        dropout_rate: 0.08,
        protocol_deviations: 2,
        completion_year: 2023,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 42,
      avg_enrollment_rate: 1.12,
      avg_screen_failure_rate: 0.19,
      avg_retention_rate: 0.91,
      regulatory_inspection_results: "No findings",
    },
  },
  {
    site_id: "SITE-003",
    site_name: "Mount Sinai Clinical Trials Unit",
    historical_trials: [
      {
        trial_id: "NCT04678901",
        phase: "Phase III",
        therapeutic_area: "Oncology",
        target_enrollment: 80,
        actual_enrollment: 78,
        enrollment_duration_days: 200,
        screen_failure_rate: 0.24,
        dropout_rate: 0.11,
        protocol_deviations: 4,
        completion_year: 2024,
      },
      {
        trial_id: "NCT04789012",
        phase: "Phase II",
        therapeutic_area: "Gastroenterology",
        target_enrollment: 45,
        actual_enrollment: 47,
        enrollment_duration_days: 160,
        screen_failure_rate: 0.22,
        dropout_rate: 0.10,
        protocol_deviations: 2,
        completion_year: 2023,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 38,
      avg_enrollment_rate: 1.05,
      avg_screen_failure_rate: 0.23,
      avg_retention_rate: 0.87,
      regulatory_inspection_results: "Minor observations corrected",
    },
  },
  {
    site_id: "SITE-005",
    site_name: "UCSF Clinical Research Center",
    historical_trials: [
      {
        trial_id: "NCT04890123",
        phase: "Phase II",
        therapeutic_area: "Oncology",
        target_enrollment: 50,
        actual_enrollment: 54,
        enrollment_duration_days: 170,
        screen_failure_rate: 0.20,
        dropout_rate: 0.09,
        protocol_deviations: 2,
        completion_year: 2024,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 45,
      avg_enrollment_rate: 1.10,
      avg_screen_failure_rate: 0.20,
      avg_retention_rate: 0.90,
      regulatory_inspection_results: "No findings",
    },
  },
  {
    site_id: "SITE-007",
    site_name: "Cedars-Sinai Medical Center Research Institute",
    historical_trials: [
      {
        trial_id: "NCT04901234",
        phase: "Phase II",
        therapeutic_area: "Pulmonology",
        target_enrollment: 55,
        actual_enrollment: 52,
        enrollment_duration_days: 190,
        screen_failure_rate: 0.25,
        dropout_rate: 0.13,
        protocol_deviations: 5,
        completion_year: 2023,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 51,
      avg_enrollment_rate: 1.02,
      avg_screen_failure_rate: 0.24,
      avg_retention_rate: 0.85,
      regulatory_inspection_results: "No findings",
    },
  },
  {
    site_id: "SITE-008",
    site_name: "MD Anderson Cancer Center Clinical Trials Office",
    historical_trials: [
      {
        trial_id: "NCT05012345",
        phase: "Phase I",
        therapeutic_area: "Oncology",
        target_enrollment: 25,
        actual_enrollment: 26,
        enrollment_duration_days: 120,
        screen_failure_rate: 0.28,
        dropout_rate: 0.15,
        protocol_deviations: 1,
        completion_year: 2024,
      },
      {
        trial_id: "NCT05123456",
        phase: "Phase II",
        therapeutic_area: "Oncology",
        target_enrollment: 60,
        actual_enrollment: 63,
        enrollment_duration_days: 155,
        screen_failure_rate: 0.26,
        dropout_rate: 0.10,
        protocol_deviations: 2,
        completion_year: 2024,
      },
    ],
    aggregate_metrics: {
      total_trials_completed: 127,
      avg_enrollment_rate: 1.15,
      avg_screen_failure_rate: 0.25,
      avg_retention_rate: 0.88,
      regulatory_inspection_results: "No findings",
    },
  },
];